export const CONFIG_KEY = {
  cabinet_payme: 'cabinet_payme',
  cabinet_click: 'cabinet_click',
  checkout_click: 'checkout_click',
  checkout_payme: 'checkout_payme',
  link_telegram: 'link_telegram',
  link_instagram: 'link_instagram',
  link_email: 'link_email',
  can_send_sms: 'can_send_sms',
  max_transfers: 'max_transfers',
  max_balance: 'max_balance',
  max_same_team_players: 'max_same_team_players',
  test_marquee: 'test_marquee',
  transfer_show_modals: 'transfer_show_modals',
  app_version: 'app_version',
  provider_google: 'provider_google',
  provider_facebook: 'provider_facebook',
  seo_title: 'seo_title',
  seo_description: 'seo_description',
}
